FROM python:3

WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install opencv-python
RUN pip install matplotlib
RUN pip install cvlib
RUN pip install tensorflow
RUN pip install psycopg2

CMD [ "python", "./objectdetection.py" ]